server:
  port: 3344

spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Oliverlyz/springcloud-config.git
          label: master
          search-paths:
            - springcloud-config

eureka:
  instance:
    instance-id: config-3344
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
